# Generated by Django 5.2.12 on 2026-04-01 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartasBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('semente', 'Semente'), ('maquina', 'Máquina'), ('fertilizante', 'Fertilizante'), ('vestuario', 'Vestuário')], max_length=20)),
                ('raridade', models.CharField(choices=[('comum', 'Comum'), ('incomum', 'Incomum'), ('raro', 'Raro'), ('epico', 'Épico'), ('lendario', 'Lendário')], max_length=20)),
                ('imagem_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moedas_ouro', models.PositiveIntegerField(default=0, verbose_name='Moedas de Ouro')),
                ('gemas_premium', models.PositiveIntegerField(default=0, verbose_name='Gemas Premium')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EdificiosJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa_nivel', models.PositiveIntegerField(default=1)),
                ('casa_skin', models.CharField(default='padrao', max_length=100)),
                ('armazem_nivel', models.PositiveIntegerField(default=1)),
                ('armazem_capacidade_maxima', models.PositiveIntegerField(default=100)),
                ('armazem_ocupacao', models.PositiveIntegerField(default=0)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='core.perfiljogador')),
            ],
            options={
                'verbose_name': 'Edifício do Jogador',
                'verbose_name_plural': 'Edifícios dos Jogadores',
            },
        ),
        migrations.CreateModel(
            name='InventarioCartas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='core.cartasbase')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_cartas', to='core.perfiljogador')),
            ],
            options={
                'verbose_name': 'Inventário de Carta',
                'verbose_name_plural': 'Inventários de Cartas',
                'unique_together': {('perfil', 'carta')},
            },
        ),
        migrations.CreateModel(
            name='EstoqueArmazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cartasbase')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='core.perfiljogador')),
            ],
            options={
                'verbose_name': 'Estoque do Armazém',
                'verbose_name_plural': 'Estoques do Armazém',
                'unique_together': {('perfil', 'item')},
            },
        ),
        migrations.CreateModel(
            name='TerrenoGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('plantado_em', models.DateTimeField(blank=True, null=True)),
                ('conclui_em', models.DateTimeField(blank=True, null=True)),
                ('carta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grids_posicionados', to='core.cartasbase')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrenos', to='core.perfiljogador')),
            ],
            options={
                'verbose_name': 'Terreno Grid',
                'verbose_name_plural': 'Terrenos Grid',
                'unique_together': {('perfil', 'x', 'y')},
            },
        ),
    ]
