# Generated by Django 5.2.12 on 2026-04-01 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartasbase_perfiljogador_edificiosjogador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiljogador',
            name='energia_atual',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='perfiljogador',
            name='energia_maxima',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='DeckJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartas', models.ManyToManyField(related_name='decks_que_participa', to='core.cartasbase')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='core.perfiljogador')),
            ],
            options={
                'verbose_name': 'Deck do Jogador',
            },
        ),
        migrations.CreateModel(
            name='EdificioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_especial', models.CharField(choices=[('poco', 'Poço Artesiano'), ('cerca', 'Cerca Reforçada'), ('espantalho', 'Espantalho Místico'), ('celeiro', 'Celeiro de Maquinário')], max_length=20)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('area_de_efeito', models.PositiveIntegerField(default=1)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios_especiais', to='core.perfiljogador')),
            ],
            options={
                'verbose_name': 'Edifício Especial (Grid)',
                'unique_together': {('perfil', 'x', 'y')},
            },
        ),
    ]
