# Generated by Django 5.2.12 on 2026-04-01 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfiljogador_energia_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartasbase',
            name='custo_recurso',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='cartasbase',
            name='recurso_tipo',
            field=models.CharField(choices=[('estamina', 'Estamina (Energia)'), ('gasolina', 'Gasolina (Combustível)')], default='estamina', max_length=15),
        ),
        migrations.AddField(
            model_name='edificioespecial',
            name='poder_defesa',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='edificioespecial',
            name='saude_atual',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='edificioespecial',
            name='saude_maxima',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='perfiljogador',
            name='escudo_ate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Escudo de Proteção Até'),
        ),
        migrations.AddField(
            model_name='perfiljogador',
            name='gasolina_atual',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='perfiljogador',
            name='gasolina_maxima',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='RegistroRaide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouro_saqueado', models.PositiveIntegerField(default=0)),
                ('sucesso', models.BooleanField(default=False)),
                ('data_raide', models.DateTimeField(auto_now_add=True)),
                ('atacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques_realizados', to='core.perfiljogador')),
                ('vitima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defesas_sofridas', to='core.perfiljogador')),
            ],
        ),
    ]
