# Generated by Django 5.2.12 on 2026-04-01 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cartasbase_custo_recurso_cartasbase_recurso_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiljogador',
            name='ultima_atualizacao_recursos',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
