# Generated by Django 5.2.12 on 2026-04-02 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartasbase',
            name='duracao_crescimento',
            field=models.PositiveIntegerField(default=5, help_text='Em minutos'),
        ),
        migrations.AddField(
            model_name='cartasbase',
            name='producao_estimada',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='perfiljogador',
            name='clima_atual',
            field=models.CharField(choices=[('clear', 'Limpo'), ('rain', 'Chuva'), ('heat', 'Calor'), ('storm', 'Tempestade')], default='clear', max_length=10),
        ),
        migrations.AddField(
            model_name='perfiljogador',
            name='clima_vencimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
